# Generated by Django 2.2.2 on 2019-06-04 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='file_name')),
                ('file_path', models.FileField(upload_to='file/resource/%Y/%m', verbose_name='file_address')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
            ],
            options={
                'verbose_name': 'file_resource',
                'verbose_name_plural': 'file_resource',
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='image_name')),
                ('file_path', models.FileField(upload_to='image/resource/%Y/%m', verbose_name='image_address')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
            ],
            options={
                'verbose_name': 'image_resource',
                'verbose_name_plural': 'image_resource',
            },
        ),
    ]
