# Generated by Django 2.2.2 on 2019-06-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='file_path',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='imageupload',
            old_name='file_path',
            new_name='image',
        ),
    ]
